/******************************************************************************/
/* File   : MemMap.h                                                          */
/*                                                                            */
/* Author : Raajnaag HULIYAPURADA MATA                                        */
/*                                                                            */
/* License / Warranty / Terms and Conditions                                  */
/*                                                                            */
/* Everyone is permitted to copy and distribute verbatim copies of this lice- */
/* nse document, but changing it is not allowed. This is a free, copyright l- */
/* icense for software and other kinds of works. By contrast, this license is */
/* intended to guarantee your freedom to share and change all versions of a   */
/* program, to make sure it remains free software for all its users. You have */
/* certain responsibilities, if you distribute copies of the software, or if  */
/* you modify it: responsibilities to respect the freedom of others.          */
/*                                                                            */
/* All rights reserved. Copyright © 1982 Raajnaag HULIYAPURADA MATA           */
/*                                                                            */
/* Always refer latest software version from:                                 */
/* https://github.com/RaajnaagHuliyapuradaMata?tab=repositories               */
/*                                                                            */
/******************************************************************************/

/******************************************************************************/
/* #INCLUDES                                                                  */
/******************************************************************************/

/******************************************************************************/
/* #DEFINES                                                                   */
/******************************************************************************/
#undef MEM_VENDOR_ID

#undef MEM_AR_MAJOR_VERSION
#undef MEM_AR_MINOR_VERSION
#undef MEM_AR_PATCH_VERSION

#undef MEM_AR_RELEASE_MAJOR_VERSION
#undef MEM_AR_RELEASE_MINOR_VERSION
#undef MEM_AR_RELEASE_PATCH_VERSION

#undef MEM_SW_MAJOR_VERSION
#undef MEM_SW_MINOR_VERSION
#undef MEM_SW_PATCH_VERSION

#define MEM_VENDOR_ID        (1u)

#define MEM_AR_RELEASE_MAJOR_VERSION       (4u)
#define MEM_AR_RELEASE_MINOR_VERSION       (0u)
#define MEM_AR_RELEASE_PATCH_VERSION       (3u)
#define MEM_SW_MAJOR_VERSION (1u)
#define MEM_SW_MINOR_VERSION (7u)
#define MEM_SW_PATCH_VERSION (0u)

#define MEMMAP_ERROR

#include "Rte_MemMap.h"

#ifdef COMM_START_SEC_CODE
#undef COMM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef COMM_STOP_SEC_CODE
#undef COMM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef COMM_START_SEC_APPL_CODE
#undef COMM_START_SEC_APPL_CODE
#define START_SEC_CODE
#endif
#ifdef COMM_STOP_SEC_APPL_CODE
#undef COMM_STOP_SEC_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef COMM_START_SEC_CONST_8BIT
#undef COMM_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef COMM_STOP_SEC_CONST_8BIT
#undef COMM_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef COMM_START_SEC_CONST_16BIT
#undef COMM_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif
#ifdef COMM_STOP_SEC_CONST_16BIT
#undef COMM_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef COMM_START_SEC_CONST_UNSPECIFIED
#undef COMM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef COMM_STOP_SEC_CONST_UNSPECIFIED
#undef COMM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef COMM_START_SEC_VAR_NOINIT_8BIT
#undef COMM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef COMM_STOP_SEC_VAR_NOINIT_8BIT
#undef COMM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef COMM_START_SEC_VAR_NOINIT_16BIT
#undef COMM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef COMM_STOP_SEC_VAR_NOINIT_16BIT
#undef COMM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef COMM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef COMM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef COMM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef COMM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef COMM_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef COMM_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef COMM_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef COMM_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef COMM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
#undef COMM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
#define START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#endif
#ifdef COMM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
#undef COMM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CANSM_START_SEC_CODE
#undef CANSM_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CANSM_STOP_SEC_CODE
#undef CANSM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CANSM_START_SEC_CONST_8BIT
#undef CANSM_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif

#ifdef CANSM_STOP_SEC_CONST_8BIT
#undef CANSM_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef CANSM_START_SEC_CONST_32BIT
#undef CANSM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif

#ifdef CANSM_STOP_SEC_CONST_32BIT
#undef CANSM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef CANSM_START_SEC_PBCFG_ROOT
#undef CANSM_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef CANSM_STOP_SEC_PBCFG_ROOT
#undef CANSM_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef CANSM_START_SEC_PBCFG
#undef CANSM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef CANSM_STOP_SEC_PBCFG
#undef CANSM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef CANSM_START_SEC_VAR_NOINIT_8BIT
#undef CANSM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif

#ifdef CANSM_STOP_SEC_VAR_NOINIT_8BIT
#undef CANSM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef CANSM_START_SEC_VAR_NOINIT_16BIT
#undef CANSM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif

#ifdef CANSM_STOP_SEC_VAR_NOINIT_16BIT
#undef CANSM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef CANSM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef CANSM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CANSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef CANSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CANSM_START_SEC_VAR_ZERO_INIT_8BIT
#undef CANSM_START_SEC_VAR_ZERO_INIT_8BIT
#define START_SEC_VAR_ZERO_INIT_8BIT
#endif

#ifdef CANSM_STOP_SEC_VAR_ZERO_INIT_8BIT
#undef CANSM_STOP_SEC_VAR_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef FRSM_START_SEC_CODE
#undef FRSM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef FRSM_STOP_SEC_CODE
#undef FRSM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef FRSM_START_SEC_CONST_32BIT
#undef FRSM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef FRSM_STOP_SEC_CONST_32BIT
#undef FRSM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef FRSM_START_SEC_CONST_UNSPECIFIED
#undef FRSM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef FRSM_STOP_SEC_CONST_UNSPECIFIED
#undef FRSM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef FRSM_START_SEC_PBCFG_ROOT
#undef FRSM_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef FRSM_STOP_SEC_PBCFG_ROOT
#undef FRSM_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef FRSM_START_SEC_PBCFG
#undef FRSM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef FRSM_STOP_SEC_PBCFG
#undef FRSM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef FRSM_START_SEC_VAR_NOINIT_8BIT
#undef FRSM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef FRSM_STOP_SEC_VAR_NOINIT_8BIT
#undef FRSM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef FRSM_START_SEC_VAR_NOINIT_16BIT
#undef FRSM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef FRSM_STOP_SEC_VAR_NOINIT_16BIT
#undef FRSM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef FRSM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef FRSM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef FRSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef FRSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRSM_START_SEC_VAR_ZERO_INIT_8BIT
#undef FRSM_START_SEC_VAR_ZERO_INIT_8BIT
#define START_SEC_VAR_ZERO_INIT_8BIT
#endif
#ifdef FRSM_STOP_SEC_VAR_ZERO_INIT_8BIT
#undef FRSM_STOP_SEC_VAR_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LINSM_START_SEC_CODE
#undef LINSM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef LINSM_STOP_SEC_CODE
#undef LINSM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef LINSM_START_SEC_CONST_8BIT
#undef LINSM_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef LINSM_STOP_SEC_CONST_8BIT
#undef LINSM_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef LINSM_START_SEC_CONST_32BIT
#undef LINSM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef LINSM_STOP_SEC_CONST_32BIT
#undef LINSM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef LINSM_START_SEC_CONST_UNSPECIFIED
#undef LINSM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef LINSM_STOP_SEC_CONST_UNSPECIFIED
#undef LINSM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef LINSM_START_SEC_PBCFG
#undef LINSM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef LINSM_STOP_SEC_PBCFG
#undef LINSM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef LINSM_START_SEC_VAR_NOINIT_16BIT
#undef LINSM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef LINSM_STOP_SEC_VAR_NOINIT_16BIT
#undef LINSM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef LINSM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef LINSM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef LINSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef LINSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef LINSM_START_SEC_VAR_ZERO_INIT_8BIT
#undef LINSM_START_SEC_VAR_ZERO_INIT_8BIT
#define START_SEC_VAR_ZERO_INIT_8BIT
#endif
#ifdef LINSM_STOP_SEC_VAR_ZERO_INIT_8BIT
#undef LINSM_STOP_SEC_VAR_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef CDD_START_SEC_CODE
#undef CDD_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef CDD_STOP_SEC_CODE
#undef CDD_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CDD_LINTP_START_SEC_CODE
#undef CDD_LINTP_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef CDD_LINTP_STOP_SEC_CODE
#undef CDD_LINTP_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef XCP_START_SEC_CODE
#undef XCP_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef XCP_STOP_SEC_CODE
#undef XCP_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef XCP_START_SEC_CONST_UNSPECIFIED
#undef XCP_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef XCP_STOP_SEC_CONST_UNSPECIFIED
#undef XCP_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef XCP_START_SEC_CONST_16BIT
#undef XCP_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif

#ifdef XCP_STOP_SEC_CONST_16BIT
#undef XCP_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef XCP_START_SEC_CONST_8BIT
#undef XCP_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif

#ifdef XCP_STOP_SEC_CONST_8BIT
#undef XCP_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef XCP_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef XCP_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef XCP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef XCP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef XCP_START_SEC_VAR_NOINIT_8BIT
#undef XCP_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif

#ifdef XCP_STOP_SEC_VAR_NOINIT_8BIT
#undef XCP_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef CANXCP_START_SEC_CODE
#undef CANXCP_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CANXCP_STOP_SEC_CODE
#undef CANXCP_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CANXCP_START_SEC_CONST_8BIT
#undef CANXCP_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif

#ifdef CANXCP_STOP_SEC_CONST_8BIT
#undef CANXCP_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef CANXCP_START_SEC_PBCFG_ROOT
#undef CANXCP_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif

#ifdef CANXCP_STOP_SEC_PBCFG_ROOT
#undef CANXCP_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef CANXCP_START_SEC_PBCFG
#undef CANXCP_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif

#ifdef CANXCP_STOP_SEC_PBCFG
#undef CANXCP_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef CANXCP_START_SEC_VAR_NOINIT_8BIT
#undef CANXCP_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif

#ifdef CANXCP_STOP_SEC_VAR_NOINIT_8BIT
#undef CANXCP_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef CANXCP_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef CANXCP_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CANXCP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef CANXCP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRXCP_START_SEC_CODE
#undef FRXCP_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef FRXCP_STOP_SEC_CODE
#undef FRXCP_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef FRXCP_START_SEC_CONST_UNSPECIFIED
#undef FRXCP_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef FRXCP_STOP_SEC_CONST_UNSPECIFIED
#undef FRXCP_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef FRXCP_START_SEC_CONST_16BIT
#undef FRXCP_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif

#ifdef FRXCP_STOP_SEC_CONST_16BIT
#undef FRXCP_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef FRXCP_START_SEC_CONST_8BIT
#undef FRXCP_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif

#ifdef FRXCP_STOP_SEC_CONST_8BIT
#undef FRXCP_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef FRXCP_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef FRXCP_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef FRXCP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef FRXCP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRXCP_START_SEC_VAR_NOINIT_8BIT
#undef FRXCP_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif

#ifdef FRXCP_STOP_SEC_VAR_NOINIT_8BIT
#undef FRXCP_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef DCM_START_SEC_CONST_8
#undef DCM_START_SEC_CONST_8
#define START_SEC_CONST_8BIT
#endif

#ifdef DCM_START_SEC_CONST_16
#undef DCM_START_SEC_CONST_16
#define START_SEC_CONST_16BIT
#endif

#ifdef DCM_START_SEC_CONST_32
#undef DCM_START_SEC_CONST_32
#define START_SEC_CONST_32BIT
#endif

#ifdef DCM_START_SEC_CONST_UNSPECIFIED
#undef DCM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef DCM_START_SEC_VAR_NO_INIT_8
#undef DCM_START_SEC_VAR_NO_INIT_8
#define START_SEC_VAR_NOINIT_8BIT
#endif

#ifdef DCM_START_SEC_VAR_NO_INIT_16
#undef DCM_START_SEC_VAR_NO_INIT_16
#define START_SEC_VAR_NOINIT_16BIT
#endif

#ifdef DCM_START_SEC_VAR_NO_INIT_32
#undef DCM_START_SEC_VAR_NO_INIT_32
#define START_SEC_VAR_NO_INIT_32BIT
#endif

#ifdef DCM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef DCM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef DCM_START_SEC_CODE
#undef DCM_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef DCM_START_SEC_APPL_CODE
#undef DCM_START_SEC_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef DCM_START_SEC_CALLOUT_CODE
#undef DCM_START_SEC_CALLOUT_CODE
#define START_SEC_CODE
#endif

#ifdef DCM_STOP_SEC_CONST_8
#undef DCM_STOP_SEC_CONST_8
#define STOP_SEC_CONST
#endif

#ifdef DCM_STOP_SEC_CONST_16
#undef DCM_STOP_SEC_CONST_16
#define STOP_SEC_CONST
#endif

#ifdef DCM_STOP_SEC_CONST_32
#undef DCM_STOP_SEC_CONST_32
#define STOP_SEC_CONST
#endif

#ifdef DCM_STOP_SEC_CONST_UNSPECIFIED
#undef DCM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef DCM_STOP_SEC_VAR_NO_INIT_8
#undef DCM_STOP_SEC_VAR_NO_INIT_8
#define STOP_SEC_VAR
#endif

#ifdef DCM_STOP_SEC_VAR_NO_INIT_16
#undef DCM_STOP_SEC_VAR_NO_INIT_16
#define STOP_SEC_VAR
#endif

#ifdef DCM_STOP_SEC_VAR_NO_INIT_32
#undef DCM_STOP_SEC_VAR_NO_INIT_32
#define STOP_SEC_VAR
#endif

#ifdef DCM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#undef DCM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef DCM_STOP_SEC_CODE
#undef DCM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef DCM_STOP_SEC_APPL_CODE
#undef DCM_STOP_SEC_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef DCM_STOP_SEC_CALLOUT_CODE
#undef DCM_STOP_SEC_CALLOUT_CODE
#define STOP_SEC_CODE
#endif

#if defined (DEM_START_SEC_CODE)
#undef DEM_START_SEC_CODE
#define START_SEC_CODE
#endif

#if defined (DEM_C_START_SEC_CODE)
#undef DEM_C_START_SEC_CODE
#define START_SEC_CODE
#endif

#if defined (DEM_START_SEC_CALLOUT_CODE)
#undef DEM_START_SEC_CALLOUT_CODE
#define START_SEC_CODE
#endif

#if defined (DEM_START_SEC_CODE_LIB)
#undef DEM_START_SEC_CODE_LIB
#define START_SEC_CODE
#endif

#if defined (DEM_START_SEC_VAR_NO_INIT_8)
#undef DEM_START_SEC_VAR_NO_INIT_8
#define START_SEC_VAR_NOINIT_8BIT
#endif
#if defined (DEM_START_SEC_VAR_NO_INIT_16)
#undef DEM_START_SEC_VAR_NO_INIT_16
#define START_SEC_VAR_NOINIT_16BIT
#endif
#if defined (DEM_START_SEC_VAR_NO_INIT_32)
#undef DEM_START_SEC_VAR_NO_INIT_32
#define START_SEC_VAR_NOINIT_32BIT
#endif
#if defined (DEM_START_SEC_VAR_NO_INIT_UNSPECIFIED)
#undef DEM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#if defined (DEM_C_START_SEC_VAR_NOINIT_8BIT)
#undef DEM_C_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#if defined (DEM_C_START_SEC_VAR_NOINIT_16BIT)
#undef DEM_C_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#if defined (DEM_C_START_SEC_VAR_NOINIT_32BIT)
#undef DEM_C_START_SEC_VAR_NOINIT_32BIT
#define START_SEC_VAR_NOINIT_32BIT
#endif
#if defined (DEM_C_START_SEC_VAR_NOINIT_UNSPECIFIED)
#undef DEM_C_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#if defined (DEM_START_SEC_VAR_INIT_8)
#undef DEM_START_SEC_VAR_INIT_8
#define START_SEC_VAR_INIT_8BIT
#endif
#if defined (DEM_START_SEC_VAR_INIT_32)
#undef DEM_START_SEC_VAR_INIT_32
#define START_SEC_VAR_INIT_32BIT
#endif

#if defined (DEM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
#undef DEM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#if defined (DEM_C_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
#undef DEM_C_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#if defined (DEM_START_SEC_CONST_SAVED_RECOVERY_ZONE0)
#undef DEM_START_SEC_CONST_SAVED_RECOVERY_ZONE0
#define START_SEC_CONST_UNSPECIFIED
#endif

#if defined (DEM_START_SEC_CONST_8)
#undef DEM_START_SEC_CONST_8
#define START_SEC_CONST_8BIT
#endif
#if defined (DEM_START_SEC_CONST_16)
#undef DEM_START_SEC_CONST_16
#define START_SEC_CONST_16BIT
#endif
#if defined (DEM_START_SEC_CONST_32)
#undef DEM_START_SEC_CONST_32
#define START_SEC_CONST_32BIT
#endif
#if defined (DEM_START_SEC_CONST_UNSPECIFIED)
#undef DEM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#if defined (DEM_C_START_SEC_CONST_8BIT)
#undef DEM_C_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#if defined (DEM_C_START_SEC_CONST_16BIT)
#undef DEM_C_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif
#if defined (DEM_C_START_SEC_CONST_32BIT)
#undef DEM_C_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#if defined (DEM_C_START_SEC_CONST_UNSPECIFIED)
#undef DEM_C_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#if defined (DEM_START_SEC_CONFIG_DATA_UNSPECIFIED)
#undef DEM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#if defined (DEM_C_START_SEC_CONST_ROOT)
#undef DEM_C_START_SEC_CONST_ROOT
#define START_SEC_CONST_PBCFG
#endif

#if defined (DEM_STOP_SEC_CODE)
#undef DEM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#if defined (DEM_C_STOP_SEC_CODE)
#undef DEM_C_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#if defined (DEM_STOP_SEC_CALLOUT_CODE)
#undef DEM_STOP_SEC_CALLOUT_CODE
#define STOP_SEC_CODE
#endif

#if defined (DEM_STOP_SEC_CODE_LIB)
#undef DEM_STOP_SEC_CODE_LIB
#define STOP_SEC_CODE
#endif

#if defined (DEM_STOP_SEC_VAR_NO_INIT_8)
#undef DEM_STOP_SEC_VAR_NO_INIT_8
#define STOP_SEC_VAR
#endif
#if defined (DEM_STOP_SEC_VAR_NO_INIT_16)
#undef DEM_STOP_SEC_VAR_NO_INIT_16
#define STOP_SEC_VAR
#endif
#if defined (DEM_STOP_SEC_VAR_NO_INIT_32)
#undef DEM_STOP_SEC_VAR_NO_INIT_32
#define STOP_SEC_VAR
#endif
#if defined (DEM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
#undef DEM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#if defined (DEM_C_STOP_SEC_VAR_NOINIT_8BIT)
#undef DEM_C_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif
#if defined (DEM_C_STOP_SEC_VAR_NOINIT_16BIT)
#undef DEM_C_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif
#if defined (DEM_C_STOP_SEC_VAR_NOINIT_32BIT)
#undef DEM_C_STOP_SEC_VAR_NOINIT_32BIT
#define STOP_SEC_VAR
#endif
#if defined (DEM_C_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#undef DEM_C_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#if defined (DEM_STOP_SEC_VAR_INIT_8)
#undef DEM_STOP_SEC_VAR_INIT_8
#define STOP_SEC_VAR
#endif
#if defined (DEM_STOP_SEC_VAR_INIT_32)
#undef DEM_STOP_SEC_VAR_INIT_32
#define STOP_SEC_VAR
#endif

#if defined (DEM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
#undef DEM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#if defined (DEM_C_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
#undef DEM_C_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#if defined (DEM_STOP_SEC_CONST_SAVED_RECOVERY_ZONE0)
#undef DEM_STOP_SEC_CONST_SAVED_RECOVERY_ZONE0
#define STOP_SEC_CONST
#endif

#if defined (DEM_STOP_SEC_CONST_8)
#undef DEM_STOP_SEC_CONST_8
#define STOP_SEC_CONST
#endif
#if defined (DEM_STOP_SEC_CONST_16)
#undef DEM_STOP_SEC_CONST_16
#define STOP_SEC_CONST
#endif
#if defined (DEM_STOP_SEC_CONST_32)
#undef DEM_STOP_SEC_CONST_32
#define STOP_SEC_CONST
#endif
#if defined (DEM_STOP_SEC_CONST_UNSPECIFIED)
#undef DEM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#if defined (DEM_C_STOP_SEC_CONST_8BIT)
#undef DEM_C_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif
#if defined (DEM_C_STOP_SEC_CONST_16BIT)
#undef DEM_C_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif
#if defined (DEM_C_STOP_SEC_CONST_32BIT)
#undef DEM_C_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif
#if defined (DEM_C_STOP_SEC_CONST_UNSPECIFIED)
#undef DEM_C_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#if defined (DEM_C_STOP_SEC_CONST_ROOT)
#undef DEM_C_STOP_SEC_CONST_ROOT
#define STOP_SEC_CONST
#endif

#ifdef CAN_START_SEC_CODE
#undef CAN_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef CAN_STOP_SEC_CODE
#undef CAN_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CAN_START_SEC_STATIC_CODE
#undef CAN_START_SEC_STATIC_CODE
#define START_SEC_CODE
#endif
#ifdef CAN_STOP_SEC_STATIC_CODE
#undef CAN_STOP_SEC_STATIC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CAN_START_SEC_CODE_APPL
#undef CAN_START_SEC_CODE_APPL
#define START_SEC_CODE
#endif
#ifdef CAN_STOP_SEC_CODE_APPL
#undef CAN_STOP_SEC_CODE_APPL
#define STOP_SEC_CODE
#endif

#ifdef CAN_START_SEC_CONST_8BIT
#undef CAN_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef CAN_STOP_SEC_CONST_8BIT
#undef CAN_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef CAN_START_SEC_CONST_16BIT
#undef CAN_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif
#ifdef CAN_STOP_SEC_CONST_16BIT
#undef CAN_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef CAN_START_SEC_CONST_32BIT
#undef CAN_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef CAN_STOP_SEC_CONST_32BIT
#undef CAN_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef CAN_START_SEC_CONST_UNSPECIFIED
#undef CAN_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef CAN_STOP_SEC_CONST_UNSPECIFIED
#undef CAN_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CAN_START_SEC_PBCFG_ROOT
#undef CAN_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef CAN_STOP_SEC_PBCFG_ROOT
#undef CAN_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef CAN_START_SEC_PBCFG
#undef CAN_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef CAN_STOP_SEC_PBCFG
#undef CAN_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef CAN_START_SEC_VAR_INIT_UNSPECIFIED
#undef CAN_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#ifdef CAN_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef CAN_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CAN_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef CAN_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef CAN_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef CAN_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef DIO_START_SEC_CODE
#undef DIO_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef DIO_STOP_SEC_CODE
#undef DIO_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef DIO_START_SEC_PBCFG
#undef DIO_START_SEC_PBCFG
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef DIO_STOP_SEC_PBCFG
#undef DIO_STOP_SEC_PBCFG
#define STOP_SEC_VAR
#endif

#ifdef FLS_START_SEC_CODE
#undef FLS_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef FLS_STOP_SEC_CODE
#undef FLS_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef FLS_START_SEC_CONST_UNSPECIFIED
#undef FLS_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef FLS_STOP_SEC_CONST_UNSPECIFIED
#undef FLS_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef FR_START_SEC_CODE
#undef FR_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef FR_STOP_SEC_CODE
#undef FR_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef FR_START_SEC_CODE_ISR
#undef FR_START_SEC_CODE_ISR
#define START_SEC_CODE_ISR
#endif
#ifdef FR_STOP_SEC_CODE_ISR
#undef FR_STOP_SEC_CODE_ISR
#define STOP_SEC_CODE
#endif

#ifdef FR_APPL_START_SEC_CODE
#undef FR_APPL_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef FR_APPL_STOP_SEC_CODE
#undef FR_APPL_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef FR_START_SEC_CONST_32BIT
#undef FR_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef FR_STOP_SEC_CONST_32BIT
#undef FR_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef FR_START_SEC_CONST_16BIT
#undef FR_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif
#ifdef FR_STOP_SEC_CONST_16BIT
#undef FR_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef FR_START_SEC_CONST_8BIT
#undef FR_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef FR_STOP_SEC_CONST_8BIT
#undef FR_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef FR_START_SEC_CONST_UNSPECIFIED
#undef FR_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef FR_STOP_SEC_CONST_UNSPECIFIED
#undef FR_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef FR_START_SEC_PBCFG_ROOT
#undef FR_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef FR_STOP_SEC_PBCFG_ROOT
#undef FR_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef FR_START_SEC_PBCFG
#undef FR_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef FR_STOP_SEC_PBCFG
#undef FR_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef FR_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef FR_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef FR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef FR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FR_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef FR_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#endif
#ifdef FR_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef FR_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef GPT_START_SEC_CODE
#undef GPT_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef GPT_STOP_SEC_CODE
#undef GPT_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef GPT_START_SEC_PBCFG
#undef GPT_START_SEC_PBCFG
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef GPT_STOP_SEC_PBCFG
#undef GPT_STOP_SEC_PBCFG
#define STOP_SEC_VAR
#endif

#ifdef LIN_START_SEC_CODE
#undef LIN_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef LIN_STOP_SEC_CODE
#undef LIN_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef LIN_START_SEC_CODE_ISR
#undef LIN_START_SEC_CODE_ISR
#define START_SEC_CODE_ISR
#endif
#ifdef LIN_STOP_SEC_CODE_ISR
#undef LIN_STOP_SEC_CODE_ISR
#define STOP_SEC_CODE
#endif

#ifdef LIN_START_SEC_CONST_8BIT
#undef LIN_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef LIN_STOP_SEC_CONST_8BIT
#undef LIN_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef LIN_START_SEC_CONST_32BIT
#undef LIN_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef LIN_STOP_SEC_CONST_32BIT
#undef LIN_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef LIN_START_SEC_CONST_UNSPECIFIED
#undef LIN_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef LIN_STOP_SEC_CONST_UNSPECIFIED
#undef LIN_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef LIN_START_SEC_PBCFG_ROOT
#undef LIN_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef LIN_STOP_SEC_PBCFG_ROOT
#undef LIN_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef LIN_START_SEC_PBCFG
#undef LIN_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef LIN_STOP_SEC_PBCFG
#undef LIN_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef LIN_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef LIN_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef LIN_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef LIN_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef LIN_START_SEC_VAR_NOINIT_8BIT
#undef LIN_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef LIN_STOP_SEC_VAR_NOINIT_8BIT
#undef LIN_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LIN_START_SEC_VAR_ZERO_INIT_8BIT
#undef LIN_START_SEC_VAR_ZERO_INIT_8BIT
#define START_SEC_VAR_ZERO_INIT_8BIT
#endif
#ifdef LIN_STOP_SEC_VAR_ZERO_INIT_8BIT
#undef LIN_STOP_SEC_VAR_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef PWM_START_SEC_CODE
#undef PWM_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef PWM_START_SEC_PBCFG
#undef PWM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif

#ifdef PWM_START_SEC_VAR_32BIT
#undef PWM_START_SEC_VAR_32BIT
#define START_SEC_VAR_INIT_32BIT
#endif

#ifdef PWM_START_SEC_VAR_NOINIT_16BIT
#undef PWM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif

#ifdef PWM_START_SEC_VAR_NOINIT_8BIT
#undef PWM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif

#ifdef PWM_STOP_SEC_CODE
#undef PWM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef PWM_STOP_SEC_PBCFG
#undef PWM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef PWM_STOP_SEC_VAR_32BIT
#undef PWM_STOP_SEC_VAR_32BIT
#define STOP_SEC_VAR
#endif

#ifdef PWM_STOP_SEC_VAR_NOINIT_16BIT
#undef PWM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef PWM_STOP_SEC_VAR_NOINIT_8BIT
#undef PWM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef SPI_START_SEC_CODE
#undef SPI_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef SPI_STOP_SEC_CODE
#undef SPI_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef IOHWAB_START_SEC_CODE
#undef IOHWAB_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef IOHWAB_STOP_SEC_CODE
#undef IOHWAB_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef IOHWAB_START_SEC_CONST_32
#undef IOHWAB_START_SEC_CONST_32
#define START_SEC_CONST_32
#endif
#ifdef IOHWAB_STOP_SEC_CONST_32
#undef IOHWAB_STOP_SEC_CONST_32
#define STOP_SEC_CONST
#endif

#ifdef IOHWAB_START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef IOHWAB_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define START_SEC_VAR_NO_INIT_UNSPECIFIED
#endif
#ifdef IOHWAB_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#undef IOHWAB_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef PDUR_START_SEC_CODE
#undef PDUR_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef PDUR_STOP_SEC_CODE
#undef PDUR_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef PDUR_START_SEC_CONST_8BIT
#undef PDUR_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef PDUR_STOP_SEC_CONST_8BIT
#undef PDUR_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef PDUR_START_SEC_CONST_16BIT
#undef PDUR_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif
#ifdef PDUR_STOP_SEC_CONST_16BIT
#undef PDUR_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef PDUR_START_SEC_CONST_32BIT
#undef PDUR_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef PDUR_STOP_SEC_CONST_32BIT
#undef PDUR_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef PDUR_START_SEC_CONST_UNSPECIFIED
#undef PDUR_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef PDUR_STOP_SEC_CONST_UNSPECIFIED
#undef PDUR_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef PDUR_START_SEC_PBCFG
#undef PDUR_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef PDUR_STOP_SEC_PBCFG
#undef PDUR_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef PDUR_START_SEC_PBCFG_ROOT
#undef PDUR_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef PDUR_STOP_SEC_PBCFG_ROOT
#undef PDUR_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef PDUR_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef PDUR_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef PDUR_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef PDUR_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef PDUR_START_SEC_VAR_NOINIT_BOOLEAN
#undef PDUR_START_SEC_VAR_NOINIT_BOOLEAN
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef PDUR_STOP_SEC_VAR_NOINIT_BOOLEAN
#undef PDUR_STOP_SEC_VAR_NOINIT_BOOLEAN
#define STOP_SEC_VAR
#endif

#ifdef PDUR_START_SEC_VAR_NOINIT_8BIT
#undef PDUR_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef PDUR_STOP_SEC_VAR_NOINIT_8BIT
#undef PDUR_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef PDUR_START_SEC_VAR_NOINIT_16BIT
#undef PDUR_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef PDUR_STOP_SEC_VAR_NOINIT_16BIT
#undef PDUR_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef LINIF_START_SEC_CODE
#undef LINIF_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef LINIF_STOP_SEC_CODE
#undef LINIF_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef LINIF_START_SEC_CONST_8BIT
#undef LINIF_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef LINIF_STOP_SEC_CONST_8BIT
#undef LINIF_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef LINIF_START_SEC_CONST_32BIT
#undef LINIF_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef LINIF_STOP_SEC_CONST_32BIT
#undef LINIF_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef LINIF_START_SEC_CONST_UNSPECIFIED
#undef LINIF_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef LINIF_STOP_SEC_CONST_UNSPECIFIED
#undef LINIF_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef LINIF_START_SEC_PBCFG_ROOT
#undef LINIF_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef LINIF_STOP_SEC_PBCFG_ROOT
#undef LINIF_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef LINIF_START_SEC_PBCFG
#undef LINIF_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef LINIF_STOP_SEC_PBCFG
#undef LINIF_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef LINIF_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef LINIF_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef LINIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef LINIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef LINIF_START_SEC_VAR_NOINIT_8BIT
#undef LINIF_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef LINIF_STOP_SEC_VAR_NOINIT_8BIT
#undef LINIF_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LINIF_START_SEC_VAR_ZERO_INIT_8BIT
#undef LINIF_START_SEC_VAR_ZERO_INIT_8BIT
#define START_SEC_VAR_ZERO_INIT_8BIT
#endif
#ifdef LINIF_STOP_SEC_VAR_ZERO_INIT_8BIT
#undef LINIF_STOP_SEC_VAR_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LINTP_START_SEC_CODE
#undef LINTP_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef LINTP_STOP_SEC_CODE
#undef LINTP_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef LINTP_START_SEC_CONST_8BIT
#undef LINTP_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef LINTP_STOP_SEC_CONST_8BIT
#undef LINTP_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef LINTP_START_SEC_CONST_32BIT
#undef LINTP_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef LINTP_STOP_SEC_CONST_32BIT
#undef LINTP_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef LINTP_START_SEC_CONST_UNSPECIFIED
#undef LINTP_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef LINTP_STOP_SEC_CONST_UNSPECIFIED
#undef LINTP_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef LINTP_START_SEC_PBCFG_ROOT
#undef LINTP_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef LINTP_STOP_SEC_PBCFG_ROOT
#undef LINTP_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef LINTP_START_SEC_PBCFG
#undef LINTP_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef LINTP_STOP_SEC_PBCFG
#undef LINTP_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef LINTP_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef LINTP_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef LINTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef LINTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef LINTP_START_SEC_VAR_NOINIT_8BIT
#undef LINTP_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef LINTP_STOP_SEC_VAR_NOINIT_8BIT
#undef LINTP_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LINTP_START_SEC_VAR_ZERO_INIT_8BIT
#undef LINTP_START_SEC_VAR_ZERO_INIT_8BIT
#define START_SEC_VAR_ZERO_INIT_8BIT
#endif
#ifdef LINTP_STOP_SEC_VAR_ZERO_INIT_8BIT
#undef LINTP_STOP_SEC_VAR_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef CANIF_START_SEC_CODE
#undef CANIF_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CANIF_STOP_SEC_CODE
#undef CANIF_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CANIF_START_SEC_APPL_CODE
#undef CANIF_START_SEC_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef CANIF_STOP_SEC_APPL_CODE
#undef CANIF_STOP_SEC_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef CANIF_START_SEC_CONST_8BIT
#undef CANIF_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif

#ifdef CANIF_STOP_SEC_CONST_8BIT
#undef CANIF_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef CANIF_START_SEC_CONST_32BIT
#undef CANIF_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif

#ifdef CANIF_STOP_SEC_CONST_32BIT
#undef CANIF_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef CANIF_START_SEC_CONST_UNSPECIFIED
#undef CANIF_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef CANIF_STOP_SEC_CONST_UNSPECIFIED
#undef CANIF_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CANIF_START_SEC_PBCFG
#undef CANIF_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif

#ifdef CANIF_STOP_SEC_PBCFG
#undef CANIF_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef CANIF_START_SEC_PBCFG_ROOT
#undef CANIF_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif

#ifdef CANIF_STOP_SEC_PBCFG_ROOT
#undef CANIF_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CANIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef CANIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef CANIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef CANIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CANIF_START_SEC_VAR_INIT_UNSPECIFIED
#undef CANIF_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef CANIF_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef CANIF_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FEE_START_SEC_CODE
#undef FEE_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef FEE_STOP_SEC_CODE
#undef FEE_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef FEE_START_SEC_CONST_UNSPECIFIED
#undef FEE_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef FEE_STOP_SEC_CONST_UNSPECIFIED
#undef FEE_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef FEE_START_SEC_APPL_CONFIG_UNSPECIFIED
#undef FEE_START_SEC_APPL_CONFIG_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef FEE_STOP_SEC_APPL_CONFIG_UNSPECIFIED
#undef FEE_STOP_SEC_APPL_CONFIG_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef FEE_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef FEE_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef FEE_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef FEE_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FEE_START_SEC_VAR_INIT_UNSPECIFIED
#undef FEE_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#ifdef FEE_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef FEE_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRIF_START_SEC_CODE
#undef FRIF_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef FRIF_STOP_SEC_CODE
#undef FRIF_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef FRIF_START_SEC_APPL_CODE
#undef FRIF_START_SEC_APPL_CODE
#define START_SEC_CODE
#endif
#ifdef FRIF_STOP_SEC_APPL_CODE
#undef FRIF_STOP_SEC_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef FRIF_START_SEC_CONST_32BIT
#undef FRIF_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef FRIF_STOP_SEC_CONST_32BIT
#undef FRIF_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef FRIF_START_SEC_CONST_UNSPECIFIED
#undef FRIF_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef FRIF_STOP_SEC_CONST_UNSPECIFIED
#undef FRIF_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef FRIF_START_SEC_PBCFG
#undef FRIF_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef FRIF_STOP_SEC_PBCFG
#undef FRIF_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef FRIF_START_SEC_PBCFG_ROOT
#undef FRIF_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef FRIF_STOP_SEC_PBCFG_ROOT
#undef FRIF_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef FRIF_START_SEC_VAR_INIT_UNSPECIFIED
#undef FRIF_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#ifdef FRIF_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef FRIF_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRIF_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef FRIF_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef FRIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef FRIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef FRIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef FRIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef FRIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef MEMIF_START_SEC_CONST_8BIT
#undef MEMIF_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif

#ifdef MEMIF_STOP_SEC_CONST_8BIT
#undef MEMIF_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef MEMIF_START_SEC_CONST_32BIT
#undef MEMIF_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif

#ifdef MEMIF_STOP_SEC_CONST_32BIT
#undef MEMIF_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef MEMIF_START_SEC_CODE
#undef MEMIF_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef MEMIF_STOP_SEC_CODE
#undef MEMIF_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef WDGIF_START_SEC_CODE
#undef WDGIF_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef WDGIF_STOP_SEC_CODE
#undef WDGIF_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef WDGIF_START_SEC_CONST_8
#undef WDGIF_START_SEC_CONST_8
#define START_SEC_CONST_8
#endif
#ifdef WDGIF_STOP_SEC_CONST_8
#undef WDGIF_STOP_SEC_CONST_8
#define STOP_SEC_CONST
#endif

#ifdef WDGIF_START_SEC_CONST_32
#undef WDGIF_START_SEC_CONST_32
#define START_SEC_CONST_32
#endif
#ifdef WDGIF_STOP_SEC_CONST_32
#undef WDGIF_STOP_SEC_CONST_32
#define STOP_SEC_CONST
#endif

#ifdef WDGIF_START_SEC_CONST_UNSPECIFIED
#undef WDGIF_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef WDGIF_STOP_SEC_CONST_UNSPECIFIED
#undef WDGIF_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef COM_START_SEC_CODE
#undef COM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef COM_STOP_SEC_CODE
#undef COM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef COM_START_SEC_APPL_CODE
#undef COM_START_SEC_APPL_CODE
#define START_SEC_CODE
#endif
#ifdef COM_STOP_SEC_APPL_CODE
#undef COM_STOP_SEC_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef COM_START_SEC_CONST_32BIT
#undef COM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef COM_STOP_SEC_CONST_32BIT
#undef COM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef COM_START_SEC_CONST_UNSPECIFIED
#undef COM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef COM_STOP_SEC_CONST_UNSPECIFIED
#undef COM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef COM_START_SEC_PBCFG_ROOT
#undef COM_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef COM_STOP_SEC_PBCFG_ROOT
#undef COM_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef COM_START_SEC_PBCFG
#undef COM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef COM_STOP_SEC_PBCFG
#undef COM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef COM_START_SEC_VAR_INIT_UNSPECIFIED
#undef COM_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#ifdef COM_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef COM_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef COM_START_SEC_VAR_NOINIT_BOOLEAN
#undef COM_START_SEC_VAR_NOINIT_BOOLEAN
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef COM_STOP_SEC_VAR_NOINIT_BOOLEAN
#undef COM_STOP_SEC_VAR_NOINIT_BOOLEAN
#define STOP_SEC_VAR
#endif

#ifdef COM_START_SEC_VAR_NOINIT_8BIT
#undef COM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef COM_STOP_SEC_VAR_NOINIT_8BIT
#undef COM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef COM_START_SEC_VAR_NOINIT_16BIT
#undef COM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef COM_STOP_SEC_VAR_NOINIT_16BIT
#undef COM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef COM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef COM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef IPDUM_START_SEC_CODE
#undef IPDUM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef IPDUM_STOP_SEC_CODE
#undef IPDUM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef IPDUM_START_SEC_PBCFG_8BIT
#undef IPDUM_START_SEC_PBCFG_8BIT
#define START_SEC_CONST_PBCFG
#endif
#ifdef IPDUM_STOP_SEC_PBCFG_8BIT
#undef IPDUM_STOP_SEC_PBCFG_8BIT
#define STOP_SEC_CONST
#endif

#ifdef IPDUM_START_SEC_PBCFG_16BIT
#undef IPDUM_START_SEC_PBCFG_16BIT
#define START_SEC_CONST_PBCFG
#endif
#ifdef IPDUM_STOP_SEC_PBCFG_16BIT
#undef IPDUM_STOP_SEC_PBCFG_16BIT
#define STOP_SEC_CONST
#endif

#ifdef IPDUM_START_SEC_PBCFG_32BIT
#undef IPDUM_START_SEC_PBCFG_32BIT
#define START_SEC_CONST_PBCFG
#endif
#ifdef IPDUM_STOP_SEC_PBCFG_32BIT
#undef IPDUM_STOP_SEC_PBCFG_32BIT
#define STOP_SEC_CONST
#endif

#ifdef IPDUM_START_SEC_PBCFG_UNSPECIFIED
#undef IPDUM_START_SEC_PBCFG_UNSPECIFIED
#define START_SEC_CONST_PBCFG
#endif
#ifdef IPDUM_STOP_SEC_PBCFG_UNSPECIFIED
#undef IPDUM_STOP_SEC_PBCFG_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef IPDUM_START_SEC_PBCFG
#undef IPDUM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef IPDUM_STOP_SEC_PBCFG
#undef IPDUM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef IPDUM_START_SEC_PBCFG_ROOT
#undef IPDUM_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef IPDUM_STOP_SEC_PBCFG_ROOT
#undef IPDUM_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef IPDUM_START_SEC_VAR_INIT_UNSPECIFIED
#undef IPDUM_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#ifdef IPDUM_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef IPDUM_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef IPDUM_START_SEC_VAR_NOINIT_8BIT
#undef IPDUM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef IPDUM_STOP_SEC_VAR_NOINIT_8BIT
#undef IPDUM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef IPDUM_START_SEC_VAR_NOINIT_16BIT
#undef IPDUM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef IPDUM_STOP_SEC_VAR_NOINIT_16BIT
#undef IPDUM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef IPDUM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef IPDUM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef IPDUM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef IPDUM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_CODE
#undef NVM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef NVM_STOP_SEC_CODE
#undef NVM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef NVM_START_SEC_CONST_8
#undef NVM_START_SEC_CONST_8
#define START_SEC_CONST_8
#endif
#ifdef NVM_STOP_SEC_CONST_8
#undef NVM_STOP_SEC_CONST_8
#define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_16
#undef NVM_START_SEC_CONST_16
#define START_SEC_CONST_16
#endif
#ifdef NVM_STOP_SEC_CONST_16
#undef NVM_STOP_SEC_CONST_16
#define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_UNSPECIFIED
#undef NVM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_CONST_UNSPECIFIED
#undef NVM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_CONST_DESCRIPTOR_TABLE
#undef NVM_START_SEC_CONST_DESCRIPTOR_TABLE
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_CONST_DESCRIPTOR_TABLE
#undef NVM_STOP_SEC_CONST_DESCRIPTOR_TABLE
#define STOP_SEC_CONST
#endif

#ifdef NVM_START_SEC_VAR_NOINIT_8
#undef NVM_START_SEC_VAR_NOINIT_8
#define START_SEC_VAR_NOINIT_8
#endif
#ifdef NVM_STOP_SEC_VAR_NOINIT_8
#undef NVM_STOP_SEC_VAR_NOINIT_8
#define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef NVM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef NVM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_UNSPECIFIED
#undef NVM_START_SEC_VAR_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_UNSPECIFIED
#undef NVM_STOP_SEC_VAR_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_FAST_8
#undef NVM_START_SEC_VAR_FAST_8
#define START_SEC_VAR_FAST_NOINIT_8
#endif
#ifdef NVM_STOP_SEC_VAR_FAST_8
#undef NVM_STOP_SEC_VAR_FAST_8
#define STOP_SEC_VAR
#endif

#ifdef NVM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#undef NVM_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef NVM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#undef NVM_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_CODE
#undef DLT_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef DLT_STOP_SEC_CODE
#undef DLT_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef DLT_START_SEC_CODE_FAST
#undef DLT_START_SEC_CODE_FAST
#define START_SEC_CODE_FAST
#endif
#ifdef DLT_STOP_SEC_CODE_FAST
#undef DLT_STOP_SEC_CODE_FAST
#define STOP_SEC_CODE
#endif

#ifdef DLT_START_SEC_CONST_8BIT
#undef DLT_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef DLT_STOP_SEC_CONST_8BIT
#undef DLT_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef DLT_START_SEC_CONST_16BIT
#undef DLT_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif
#ifdef DLT_STOP_SEC_CONST_16BIT
#undef DLT_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef DLT_START_SEC_CONST_32BIT
#undef DLT_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef DLT_STOP_SEC_CONST_32BIT
#undef DLT_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef DLT_START_SEC_CONST_UNSPECIFIED
#undef DLT_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef DLT_STOP_SEC_CONST_UNSPECIFIED
#undef DLT_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef DLT_START_SEC_VAR_INIT_8BIT
#undef DLT_START_SEC_VAR_INIT_8BIT
#define START_SEC_VAR_INIT_8BIT
#endif
#ifdef DLT_STOP_SEC_VAR_INIT_8BIT
#undef DLT_STOP_SEC_VAR_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_INIT_16BIT
#undef DLT_START_SEC_VAR_INIT_16BIT
#define START_SEC_VAR_INIT_16BIT
#endif
#ifdef DLT_STOP_SEC_VAR_INIT_16BIT
#undef DLT_STOP_SEC_VAR_INIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_INIT_32BIT
#undef DLT_START_SEC_VAR_INIT_32BIT
#define START_SEC_VAR_INIT_32BIT
#endif
#ifdef DLT_STOP_SEC_VAR_INIT_32BIT
#undef DLT_STOP_SEC_VAR_INIT_32BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_INIT_UNSPECIFIED
#undef DLT_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#ifdef DLT_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef DLT_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_NOINIT_8BIT
#undef DLT_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef DLT_STOP_SEC_VAR_NOINIT_8BIT
#undef DLT_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_NOINIT_16BIT
#undef DLT_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef DLT_STOP_SEC_VAR_NOINIT_16BIT
#undef DLT_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_NOINIT_32BIT
#undef DLT_START_SEC_VAR_NOINIT_32BIT
#define START_SEC_VAR_NOINIT_32BIT
#endif
#ifdef DLT_STOP_SEC_VAR_NOINIT_32BIT
#undef DLT_STOP_SEC_VAR_NOINIT_32BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef DLT_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef DLT_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef DLT_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_ZERO_INIT_8BIT
#undef DLT_START_SEC_VAR_ZERO_INIT_8BIT
#define START_SEC_VAR_ZERO_INIT_8BIT
#endif
#ifdef DLT_STOP_SEC_VAR_ZERO_INIT_8BIT
#undef DLT_STOP_SEC_VAR_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_ZERO_INIT_16BIT
#undef DLT_START_SEC_VAR_ZERO_INIT_16BIT
#define START_SEC_VAR_ZERO_INIT_16BIT
#endif
#ifdef DLT_STOP_SEC_VAR_ZERO_INIT_16BIT
#undef DLT_STOP_SEC_VAR_ZERO_INIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_ZERO_INIT_32BIT
#undef DLT_START_SEC_VAR_ZERO_INIT_32BIT
#define START_SEC_VAR_ZERO_INIT_32BIT
#endif
#ifdef DLT_STOP_SEC_VAR_ZERO_INIT_32BIT
#undef DLT_STOP_SEC_VAR_ZERO_INIT_32BIT
#define STOP_SEC_VAR
#endif

#ifdef DLT_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef DLT_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif
#ifdef DLT_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef DLT_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef GENMEAS_START_SEC_CONST_8BIT
#undef GENMEAS_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef GENMEAS_STOP_SEC_CONST_8BIT
#undef GENMEAS_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef GENMEAS_START_SEC_CONST_16BIT
#undef GENMEAS_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif
#ifdef GENMEAS_STOP_SEC_CONST_16BIT
#undef GENMEAS_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef GENMEAS_START_SEC_CONST_32BIT
#undef GENMEAS_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef GENMEAS_STOP_SEC_CONST_32BIT
#undef GENMEAS_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef GENMEAS_START_SEC_CONST_UNSPECIFIED
#undef GENMEAS_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef GENMEAS_STOP_SEC_CONST_UNSPECIFIED
#undef GENMEAS_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef AMDRTM_START_SEC_CODE
#undef AMDRTM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef AMDRTM_STOP_SEC_CODE
#undef AMDRTM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef AMDRTM_START_SEC_CONST_8BIT
#undef AMDRTM_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef AMDRTM_STOP_SEC_CONST_8BIT
#undef AMDRTM_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef AMDRTM_START_SEC_CONST_16BIT
#undef AMDRTM_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif
#ifdef AMDRTM_STOP_SEC_CONST_16BIT
#undef AMDRTM_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#ifdef AMDRTM_START_SEC_CONST_32BIT
#undef AMDRTM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef AMDRTM_STOP_SEC_CONST_32BIT
#undef AMDRTM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef AMDRTM_START_SEC_VAR_INIT_16BIT
#undef AMDRTM_START_SEC_VAR_INIT_16BIT
#define START_SEC_VAR_INIT_16BIT
#endif
#ifdef AMDRTM_STOP_SEC_VAR_INIT_16BIT
#undef AMDRTM_STOP_SEC_VAR_INIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef AMDRTM_START_SEC_VAR_INIT_32BIT
#undef AMDRTM_START_SEC_VAR_INIT_32BIT
#define START_SEC_VAR_INIT_32BIT
#endif
#ifdef AMDRTM_STOP_SEC_VAR_INIT_32BIT
#undef AMDRTM_STOP_SEC_VAR_INIT_32BIT
#define STOP_SEC_VAR
#endif

#ifdef AMDRTM_START_SEC_VAR_INIT_UNSPECIFIED
#undef AMDRTM_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif
#ifdef AMDRTM_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef AMDRTM_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef AMDRTM_START_SEC_VAR_NOINIT_16BIT
#undef AMDRTM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef AMDRTM_STOP_SEC_VAR_NOINIT_16BIT
#undef AMDRTM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef AMDRTM_START_SEC_VAR_NOINIT_32BIT
#undef AMDRTM_START_SEC_VAR_NOINIT_32BIT
#define START_SEC_VAR_NOINIT_32BIT
#endif
#ifdef AMDRTM_STOP_SEC_VAR_NOINIT_32BIT
#undef AMDRTM_STOP_SEC_VAR_NOINIT_32BIT
#define STOP_SEC_VAR
#endif

#ifdef AMDRTM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef AMDRTM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef AMDRTM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef AMDRTM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CANNM_START_SEC_CODE
#undef CANNM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef CANNM_STOP_SEC_CODE
#undef CANNM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CANNM_START_SEC_CONST_8BIT
#undef CANNM_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef CANNM_STOP_SEC_CONST_8BIT
#undef CANNM_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef CANNM_START_SEC_CONST_32BIT
#undef CANNM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef CANNM_STOP_SEC_CONST_32BIT
#undef CANNM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef CANNM_START_SEC_CONST_UNSPECIFIED
#undef CANNM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef CANNM_STOP_SEC_CONST_UNSPECIFIED
#undef CANNM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CANNM_START_SEC_PBCFG_ROOT
#undef CANNM_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef CANNM_STOP_SEC_PBCFG_ROOT
#undef CANNM_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef CANNM_START_SEC_PBCFG
#undef CANNM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef CANNM_STOP_SEC_PBCFG
#undef CANNM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef CANNM_START_SEC_VAR_NOINIT_8BIT
#undef CANNM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef CANNM_STOP_SEC_VAR_NOINIT_8BIT
#undef CANNM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef CANNM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef CANNM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef CANNM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef CANNM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CANNM_START_SEC_VAR_FAST_NOINIT_8BIT
#undef CANNM_START_SEC_VAR_FAST_NOINIT_8BIT
#define START_SEC_VAR_FAST_NOINIT_8BIT
#endif
#ifdef CANNM_STOP_SEC_VAR_FAST_NOINIT_8BIT
#undef CANNM_STOP_SEC_VAR_FAST_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef CANNM_START_SEC_VAR_FAST_NOINIT_16BIT
#undef CANNM_START_SEC_VAR_FAST_NOINIT_16BIT
#define START_SEC_VAR_FAST_NOINIT_16BIT
#endif
#ifdef CANNM_STOP_SEC_VAR_FAST_NOINIT_16BIT
#undef CANNM_STOP_SEC_VAR_FAST_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef CANNM_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef CANNM_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#endif
#ifdef CANNM_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef CANNM_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CANNM_START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#undef CANNM_START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#endif
#ifdef CANNM_STOP_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#undef CANNM_STOP_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRNM_START_SEC_CODE
#undef FRNM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef FRNM_STOP_SEC_CODE
#undef FRNM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef FRNM_START_SEC_CONST_8BIT
#undef FRNM_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef FRNM_STOP_SEC_CONST_8BIT
#undef FRNM_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef FRNM_START_SEC_CONST_32BIT
#undef FRNM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef FRNM_STOP_SEC_CONST_32BIT
#undef FRNM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef FRNM_START_SEC_CONST_UNSPECIFIED
#undef FRNM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef FRNM_STOP_SEC_CONST_UNSPECIFIED
#undef FRNM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef FRNM_START_SEC_PBCFG
#undef FRNM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef FRNM_STOP_SEC_PBCFG
#undef FRNM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef FRNM_START_SEC_PBCFG_ROOT
#undef FRNM_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef FRNM_STOP_SEC_PBCFG_ROOT
#undef FRNM_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef FRNM_START_SEC_VAR_NOINIT_8BIT
#undef FRNM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef FRNM_STOP_SEC_VAR_NOINIT_8BIT
#undef FRNM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef FRNM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef FRNM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef FRNM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef FRNM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRNM_START_SEC_VAR_FAST_NOINIT_8BIT
#undef FRNM_START_SEC_VAR_FAST_NOINIT_8BIT
#define START_SEC_VAR_FAST_NOINIT_8BIT
#endif
#ifdef FRNM_STOP_SEC_VAR_FAST_NOINIT_8BIT
#undef FRNM_STOP_SEC_VAR_FAST_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef FRNM_START_SEC_VAR_FAST_NOINIT_16BIT
#undef FRNM_START_SEC_VAR_FAST_NOINIT_16BIT
#define START_SEC_VAR_FAST_NOINIT_16BIT
#endif
#ifdef FRNM_STOP_SEC_VAR_FAST_NOINIT_16BIT
#undef FRNM_STOP_SEC_VAR_FAST_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef FRNM_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef FRNM_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#endif
#ifdef FRNM_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef FRNM_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef FRNM_START_SEC_VAR_FAST_ZERO_INIT_8BIT
#undef FRNM_START_SEC_VAR_FAST_ZERO_INIT_8BIT
#define START_SEC_VAR_FAST_ZERO_INIT_8BIT
#endif
#ifdef FRNM_STOP_SEC_VAR_FAST_ZERO_INIT_8BIT
#undef FRNM_STOP_SEC_VAR_FAST_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef FRNM_START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#undef FRNM_START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#endif
#ifdef FRNM_STOP_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#undef FRNM_STOP_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef NM_START_SEC_CODE
#undef NM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef NM_STOP_SEC_CODE
#undef NM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef NM_START_SEC_CONST_8BIT
#undef NM_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef NM_STOP_SEC_CONST_8BIT
#undef NM_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef NM_START_SEC_CONST_UNSPECIFIED
#undef NM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef NM_STOP_SEC_CONST_UNSPECIFIED
#undef NM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef NM_START_SEC_VAR_FAST_NOINIT_8BIT
#undef NM_START_SEC_VAR_FAST_NOINIT_8BIT
#define START_SEC_VAR_FAST_NOINIT_8BIT
#endif
#ifdef NM_STOP_SEC_VAR_FAST_NOINIT_8BIT
#undef NM_STOP_SEC_VAR_FAST_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef NM_START_SEC_VAR_FAST_NOINIT_16BIT
#undef NM_START_SEC_VAR_FAST_NOINIT_16BIT
#define START_SEC_VAR_FAST_NOINIT_16BIT
#endif
#ifdef NM_STOP_SEC_VAR_FAST_NOINIT_16BIT
#undef NM_STOP_SEC_VAR_FAST_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef NM_START_SEC_VAR_FAST_ZERO_INIT_8BIT
#undef NM_START_SEC_VAR_FAST_ZERO_INIT_8BIT
#define START_SEC_VAR_FAST_ZERO_INIT_8BIT
#endif
#ifdef NM_STOP_SEC_VAR_FAST_ZERO_INIT_8BIT
#undef NM_STOP_SEC_VAR_FAST_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LINNM_START_SEC_CODE
#undef LINNM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef LINNM_STOP_SEC_CODE
#undef LINNM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef LINNM_START_SEC_CONST_8BIT
#undef LINNM_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif
#ifdef LINNM_STOP_SEC_CONST_8BIT
#undef LINNM_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#ifdef LINNM_START_SEC_CONST_32BIT
#undef LINNM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif
#ifdef LINNM_STOP_SEC_CONST_32BIT
#undef LINNM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef LINNM_START_SEC_CONST_UNSPECIFIED
#undef LINNM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef LINNM_STOP_SEC_CONST_UNSPECIFIED
#undef LINNM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef LINNM_START_SEC_PBCFG
#undef LINNM_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef LINNM_STOP_SEC_PBCFG
#undef LINNM_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef LINNM_START_SEC_PBCFG_ROOT
#undef LINNM_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif
#ifdef LINNM_STOP_SEC_PBCFG_ROOT
#undef LINNM_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef LINNM_START_SEC_VAR_NOINIT_8BIT
#undef LINNM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef LINNM_STOP_SEC_VAR_NOINIT_8BIT
#undef LINNM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LINNM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef LINNM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef LINNM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef LINNM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef LINNM_START_SEC_VAR_FAST_NOINIT_8BIT
#undef LINNM_START_SEC_VAR_FAST_NOINIT_8BIT
#define START_SEC_VAR_FAST_NOINIT_8BIT
#endif
#ifdef LINNM_STOP_SEC_VAR_FAST_NOINIT_8BIT
#undef LINNM_STOP_SEC_VAR_FAST_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LINNM_START_SEC_VAR_FAST_NOINIT_16BIT
#undef LINNM_START_SEC_VAR_FAST_NOINIT_16BIT
#define START_SEC_VAR_FAST_NOINIT_16BIT
#endif
#ifdef LINNM_STOP_SEC_VAR_FAST_NOINIT_16BIT
#undef LINNM_STOP_SEC_VAR_FAST_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef LINNM_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef LINNM_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#endif
#ifdef LINNM_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef LINNM_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef LINNM_START_SEC_VAR_FAST_ZERO_INIT_8BIT
#undef LINNM_START_SEC_VAR_FAST_ZERO_INIT_8BIT
#define START_SEC_VAR_FAST_ZERO_INIT_8BIT
#endif
#ifdef LINNM_STOP_SEC_VAR_FAST_ZERO_INIT_8BIT
#undef LINNM_STOP_SEC_VAR_FAST_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef LINNM_START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#undef LINNM_START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#endif
#ifdef LINNM_STOP_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#undef LINNM_STOP_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef BSWM_START_SEC_CODE
#undef BSWM_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef BSWM_STOP_SEC_CODE
#undef BSWM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef BSWM_START_SEC_CONST_UNSPECIFIED
#undef BSWM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef BSWM_STOP_SEC_CONST_UNSPECIFIED
#undef BSWM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef BSWM_START_SEC_CONST_32BIT
#undef BSWM_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif

#ifdef BSWM_STOP_SEC_CONST_32BIT
#undef BSWM_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#ifdef BSWM_START_SEC_VAR_NOINIT_8BIT
#undef BSWM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif

#ifdef BSWM_STOP_SEC_VAR_NOINIT_8BIT
#undef BSWM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef BSWM_START_SEC_VAR_NOINIT_16BIT
#undef  BSWM_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif

#ifdef BSWM_STOP_SEC_VAR_NOINIT_16BIT
#undef BSWM_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#ifdef BSWM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef BSWM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef BSWM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef BSWM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef BSWM_START_SEC_VAR_INIT_UNSPECIFIED
#undef BSWM_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef BSWM_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef BSWM_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef ECUM_START_SEC_CODE
#undef ECUM_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef ECUM_STOP_SEC_CODE
#undef ECUM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef ECUM_START_SEC_CONST_PBCFG
#undef ECUM_START_SEC_CONST_PBCFG
#define START_SEC_CONST_PBCFG
#endif
#ifdef ECUM_STOP_SEC_CONST_PBCFG
#undef ECUM_STOP_SEC_CONST_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef ECUM_START_SEC_VAR_NOINIT_8BIT
#undef ECUM_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef ECUM_STOP_SEC_VAR_NOINIT_8BIT
#undef ECUM_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef ECUM_START_SEC_VAR_NOINIT_32BIT
#undef ECUM_START_SEC_VAR_NOINIT_32BIT
#define START_SEC_VAR_NOINIT_32BIT
#endif
#ifdef ECUM_STOP_SEC_VAR_NOINIT_32BIT
#undef ECUM_STOP_SEC_VAR_NOINIT_3BIT
#define STOP_SEC_VAR
#endif

#ifdef ECUM_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef ECUM_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef ECUM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef ECUM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CRC_START_SEC_CODE
#undef CRC_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef CRC_STOP_SEC_CODE
#undef CRC_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CRC_START_SEC_CONST_8
#undef CRC_START_SEC_CONST_8
#define START_SEC_CONST_8
#endif
#ifdef CRC_STOP_SEC_CONST_8
#undef CRC_STOP_SEC_CONST_8
#define STOP_SEC_CONST
#endif

#ifdef CRC_START_SEC_CONST_16
#undef CRC_START_SEC_CONST_16
#define START_SEC_CONST_16
#endif
#ifdef CRC_STOP_SEC_CONST_16
#undef CRC_STOP_SEC_CONST_16
#define STOP_SEC_CONST
#endif

#ifdef CRC_START_SEC_CONST_32
#undef CRC_START_SEC_CONST_32
#define START_SEC_CONST_32
#endif
#ifdef CRC_STOP_SEC_CONST_32
#undef CRC_STOP_SEC_CONST_32
#define STOP_SEC_CONST
#endif

#ifdef DET_START_SEC_CODE
#undef DET_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef DET_STOP_SEC_CODE
#undef DET_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef DET_START_SEC_VAR_UNSPECIFIED
#undef DET_START_SEC_VAR_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef DET_STOP_SEC_VAR_UNSPECIFIED
#undef DET_STOP_SEC_VAR_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RAMTST_START_SEC_CODE
#undef RAMTST_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef RAMTST_STOP_SEC_CODE
#undef RAMTST_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef RAMTST_START_SEC_VAR_INIT_UNSPECIFIED
#undef RAMTST_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef RAMTST_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef RAMTST_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RAMTST_START_SEC_VAR_NO_INIT_8
#undef RAMTST_START_SEC_VAR_NO_INIT_8
#define START_SEC_VAR_NO_INIT_8
#endif

#ifdef RAMTST_STOP_SEC_VAR_NO_INIT_8
#undef RAMTST_STOP_SEC_VAR_NO_INIT_8
#define STOP_SEC_VAR
#endif

#ifdef RAMTST_START_SEC_VAR_NO_INIT_32
#undef RAMTST_START_SEC_VAR_NO_INIT_32
#define START_SEC_VAR_NO_INIT_32
#endif

#ifdef RAMTST_STOP_SEC_VAR_NO_INIT_32
#undef RAMTST_STOP_SEC_VAR_NO_INIT_32
#define STOP_SEC_VAR
#endif

#ifdef RAMTST_START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef RAMTST_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define START_SEC_VAR_NO_INIT_UNSPECIFIED
#endif

#ifdef RAMTST_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#undef RAMTST_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RAMTST_START_SEC_CONST_32
#undef RAMTST_START_SEC_CONST_32
#define START_SEC_CONST_32
#endif

#ifdef RAMTST_STOP_SEC_CONST_32
#undef RAMTST_STOP_SEC_CONST_32
#define STOP_SEC_CONST
#endif

#ifdef RAMTST_START_SEC_CONST_UNSPECIFIED
#undef RAMTST_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef RAMTST_STOP_SEC_CONST_UNSPECIFIED
#undef RAMTST_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef RAMTST_START_SEC_CONST_PBCFG
#undef RAMTST_START_SEC_CONST_PBCFG
#define START_SEC_CONST_PBCFG
#endif

#ifdef RAMTST_STOP_SEC_CONST_PBCFG
#undef RAMTST_STOP_SEC_CONST_PBCFG
#define STOP_SEC_CONST
#endif

#ifdef RAMTST_START_SEC_CONST_PBCFG_ROOT
#undef RAMTST_START_SEC_CONST_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif

#ifdef RAMTST_STOP_SEC_CONST_PBCFG_ROOT
#undef RAMTST_STOP_SEC_CONST_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#ifdef WDGM_START_SEC_CODE
#undef WDGM_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef WDGM_STOP_SEC_CODE
#undef WDGM_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef WDGM_START_SEC_CONST_UNSPECIFIED
#undef WDGM_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef WDGM_STOP_SEC_CONST_UNSPECIFIED
#undef WDGM_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef WDGM_START_SEC_CONST_32
#undef WDGM_START_SEC_CONST_32
#define START_SEC_CONST_32
#endif

#ifdef WDGM_STOP_SEC_CONST_32
#undef WDGM_STOP_SEC_CONST_32
#define STOP_SEC_CONST
#endif

#ifdef WDGM_START_SEC_CONFIG_DATA_UNSPECIFIED
#undef WDGM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define START_SEC_CONFIG_DATA_UNSPECIFIED
#endif

#ifdef WDGM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#undef WDGM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef WDGM_START_SEC_VAR_INIT_UNSPECIFIED
#undef WDGM_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef WDGM_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef WDGM_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef WDGM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef WDGM_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define START_SEC_VAR_NO_INIT_UNSPECIFIED
#endif

#ifdef WDGM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#undef WDGM_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#if defined (CANTP_START_SEC_CODE)
#undef    CANTP_START_SEC_CODE
#define         START_SEC_CODE
#endif
#if defined (CANTP_STOP_SEC_CODE)
#undef    CANTP_STOP_SEC_CODE
#define         STOP_SEC_CODE
#endif

#if defined (CANTP_START_SEC_CONST_UNSPECIFIED)
#undef    CANTP_START_SEC_CONST_UNSPECIFIED
#define         START_SEC_CONST_UNSPECIFIED
#endif
#if defined (CANTP_STOP_SEC_CONST_UNSPECIFIED)
#undef    CANTP_STOP_SEC_CONST_UNSPECIFIED
#define         STOP_SEC_CONST
#endif

#if defined (CANTP_START_SEC_VAR_INIT_UNSPECIFIED)
#undef    CANTP_START_SEC_VAR_INIT_UNSPECIFIED
#define         START_SEC_VAR_INIT_UNSPECIFIED
#endif
#if defined (CANTP_STOP_SEC_VAR_INIT_UNSPECIFIED)
#undef    CANTP_STOP_SEC_VAR_INIT_UNSPECIFIED
#define         STOP_SEC_VAR
#endif

#if defined (CANTP_START_SEC_VAR_NOINIT_UNSPECIFIED)
#undef    CANTP_START_SEC_VAR_NOINIT_UNSPECIFIED
#define         START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#if defined (CANTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#undef    CANTP_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define         STOP_SEC_VAR
#endif

#if defined (CANTP_START_SEC_VAR_NOINIT_8BIT)
#undef    CANTP_START_SEC_VAR_NOINIT_8BIT
#define         START_SEC_VAR_NOINIT_8BIT
#endif
#if defined (CANTP_STOP_SEC_VAR_NOINIT_8BIT)
#undef    CANTP_STOP_SEC_VAR_NOINIT_8BIT
#define         STOP_SEC_VAR
#endif

#if defined (CANTP_START_SEC_CONST_32BIT)
#undef    CANTP_START_SEC_CONST_32BIT
#define         START_SEC_CONST_32BIT
#endif
#if defined (CANTP_STOP_SEC_CONST_32BIT)
#undef    CANTP_STOP_SEC_CONST_32BIT
#define         STOP_SEC_CONST
#endif

#if defined (CANTP_START_SEC_CONST_PBCFG)
#undef    CANTP_START_SEC_CONST_PBCFG
#define         START_SEC_CONST_PBCFG
#endif
#if defined (CANTP_STOP_SEC_CONST_PBCFG)
#undef    CANTP_STOP_SEC_CONST_PBCFG
#define         STOP_SEC_CONST
#endif

#if defined (CANTP_START_SEC_CONST_PBCFG_ROOT)
#undef    CANTP_START_SEC_CONST_PBCFG_ROOT
#define         START_SEC_CONST_PBCFG
#endif
#if defined (CANTP_STOP_SEC_CONST_PBCFG_ROOT)
#undef    CANTP_STOP_SEC_CONST_PBCFG_ROOT
#define         STOP_SEC_CONST
#endif

#if defined (TP_ISO10681_START_SEC_CODE)
#undef      TP_ISO10681_START_SEC_CODE
#define START_SEC_CODE
#endif

#if defined (TP_ISO10681_STOP_SEC_CODE)
#undef      TP_ISO10681_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#if defined (FRTP_START_SEC_CODE)
#undef      FRTP_START_SEC_CODE
#define START_SEC_CODE
#endif

#if defined (FRTP_STOP_SEC_CODE)
#undef      FRTP_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#if defined (TP_ISO10681_START_SEC_CONST_8BIT)
#undef      TP_ISO10681_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#endif

#if defined (TP_ISO10681_STOP_SEC_CONST_8BIT)
#undef      TP_ISO10681_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST
#endif

#if defined (TP_ISO10681_START_SEC_CONST_16BIT)
#undef      TP_ISO10681_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#endif

#if defined (TP_ISO10681_STOP_SEC_CONST_16BIT)
#undef      TP_ISO10681_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST
#endif

#if defined (TP_ISO10681_START_SEC_CONST_32BIT)
#undef      TP_ISO10681_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#endif

#if defined (TP_ISO10681_STOP_SEC_CONST_32BIT)
#undef      TP_ISO10681_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST
#endif

#if defined (TP_ISO10681_START_SEC_CONST_UNSPECIFIED)
#undef      TP_ISO10681_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#if defined (TP_ISO10681_STOP_SEC_CONST_UNSPECIFIED)
#undef      TP_ISO10681_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#if defined (TP_ISO10681_START_SEC_PBCFG)
#undef      TP_ISO10681_START_SEC_PBCFG
#define START_SEC_CONST_PBCFG
#endif

#if defined (TP_ISO10681_STOP_SEC_PBCFG)
#undef      TP_ISO10681_STOP_SEC_PBCFG
#define STOP_SEC_CONST
#endif

#if defined (TP_ISO10681_START_SEC_PBCFG_ROOT)
#undef      TP_ISO10681_START_SEC_PBCFG_ROOT
#define START_SEC_CONST_PBCFG
#endif

#if defined (TP_ISO10681_STOP_SEC_PBCFG_ROOT)
#undef      TP_ISO10681_STOP_SEC_PBCFG_ROOT
#define STOP_SEC_CONST
#endif

#if defined (TP_ISO10681_START_SEC_VAR_NOINIT_8BIT)
#undef      TP_ISO10681_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#endif

#if defined (TP_ISO10681_STOP_SEC_VAR_NOINIT_8BIT)
#undef      TP_ISO10681_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR
#endif

#if defined (TP_ISO10681_START_SEC_VAR_NOINIT_16BIT)
#undef      TP_ISO10681_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#endif

#if defined (TP_ISO10681_STOP_SEC_VAR_NOINIT_16BIT)
#undef      TP_ISO10681_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR
#endif

#if defined (TP_ISO10681_START_SEC_VAR_NOINIT_32BIT)
#undef      TP_ISO10681_START_SEC_VAR_NOINIT_32BIT
#define START_SEC_VAR_NOINIT_32BIT
#endif

#if defined (TP_ISO10681_STOP_SEC_VAR_NOINIT_32BIT)
#undef      TP_ISO10681_STOP_SEC_VAR_NOINIT_32BIT
#define STOP_SEC_VAR
#endif

#if defined (TP_ISO10681_START_SEC_VAR_NOINIT_UNSPECIFIED)
#undef      TP_ISO10681_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#if defined (TP_ISO10681_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#undef      TP_ISO10681_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef VSTDLIB_START_SEC_CODE
#undef VSTDLIB_START_SEC_CODE
#define START_SEC_CODE
#endif
#ifdef VSTDLIB_STOP_SEC_CODE
#undef VSTDLIB_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef VSTDLIB_START_SEC_CONST_UNSPECIFIED
#undef VSTDLIB_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef VSTDLIB_STOP_SEC_CONST_UNSPECIFIED
#undef VSTDLIB_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef VSTDLIB_START_SEC_VAR_NOINIT_UNSPECIFIED
#undef VSTDLIB_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef VSTDLIB_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#undef VSTDLIB_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef START_SEC_CONST_8
#define START_SEC_CONST_8BIT
#undef START_SEC_CONST_8
#endif

#ifdef START_SEC_CONST_16
#define START_SEC_CONST_16BIT
#undef START_SEC_CONST_16
#endif

#ifdef START_SEC_CONST_32
#define START_SEC_CONST_32BIT
#undef START_SEC_CONST_32
#endif

#ifdef START_SEC_CONST_FAST_8
#define START_SEC_CONST_FAST_8BIT
#undef START_SEC_CONST_FAST_8
#endif

#ifdef START_SEC_CONST_FAST_16
#define START_SEC_CONST_FAST_16BIT
#undef START_SEC_CONST_FAST_16
#endif

#ifdef START_SEC_CONST_FAST_32
#define START_SEC_CONST_FAST_32BIT
#undef START_SEC_CONST_FAST_32
#endif

#ifdef START_SEC_VAR_INIT_8
#define START_SEC_VAR_INIT_8BIT
#undef START_SEC_VAR_INIT_8
#endif

#ifdef START_SEC_VAR_INIT_16
#define START_SEC_VAR_INIT_16BIT
#undef START_SEC_VAR_INIT_16
#endif

#ifdef START_SEC_VAR_INIT_32
#define START_SEC_VAR_INIT_32BIT
#undef START_SEC_VAR_INIT_32
#endif

#ifdef START_SEC_VAR_NOINIT_8
#define START_SEC_VAR_NOINIT_8BIT
#undef START_SEC_VAR_NOINIT_8
#endif

#ifdef START_SEC_VAR_NOINIT_16
#define START_SEC_VAR_NOINIT_16BIT
#undef START_SEC_VAR_NOINIT_16
#endif

#ifdef START_SEC_VAR_NOINIT_32
#define START_SEC_VAR_NOINIT_32BIT
#undef START_SEC_VAR_NOINIT_32
#endif

#ifdef START_SEC_VAR_ZERO_INIT_8
#define START_SEC_VAR_ZERO_INIT_8BIT
#undef START_SEC_VAR_ZERO_INIT_8
#endif

#ifdef START_SEC_VAR_ZERO_INIT_16
#define START_SEC_VAR_ZERO_INIT_16BIT
#undef START_SEC_VAR_ZERO_INIT_16
#endif

#ifdef START_SEC_VAR_ZERO_INIT_32
#define START_SEC_VAR_ZERO_INIT_32BIT
#undef START_SEC_VAR_ZERO_INIT_32
#endif

#ifdef START_SEC_VAR_FAST_INIT_8
#define START_SEC_VAR_FAST_INIT_8BIT
#undef START_SEC_VAR_FAST_INIT_8
#endif

#ifdef START_SEC_VAR_FAST_INIT_16
#define START_SEC_VAR_FAST_INIT_16BIT
#undef START_SEC_VAR_FAST_INIT_16
#endif

#ifdef START_SEC_VAR_FAST_INIT_32
#define START_SEC_VAR_FAST_INIT_32BIT
#undef START_SEC_VAR_FAST_INIT_32
#endif

#ifdef START_SEC_VAR_FAST_NOINIT_8
#define START_SEC_VAR_FAST_NOINIT_8BIT
#undef START_SEC_VAR_FAST_NOINIT_8
#endif

#ifdef START_SEC_VAR_FAST_NOINIT_16
#define START_SEC_VAR_FAST_NOINIT_16BIT
#undef START_SEC_VAR_FAST_NOINIT_16
#endif

#ifdef START_SEC_VAR_FAST_NOINIT_32
#define START_SEC_VAR_FAST_NOINIT_32BIT
#undef START_SEC_VAR_FAST_NOINIT_32
#endif

#ifdef START_SEC_VAR_FAST_ZERO_INIT_8
#define START_SEC_VAR_FAST_ZERO_INIT_8BIT
#undef START_SEC_VAR_FAST_ZERO_INIT_8
#endif

#ifdef START_SEC_VAR_FAST_ZERO_INIT_16
#define START_SEC_VAR_FAST_ZERO_INIT_16BIT
#undef START_SEC_VAR_FAST_ZERO_INIT_16
#endif

#ifdef START_SEC_VAR_FAST_ZERO_INIT_32
#define START_SEC_VAR_FAST_ZERO_INIT_32BIT
#undef START_SEC_VAR_FAST_ZERO_INIT_32
#endif

#if((defined CODE_SEC_OPEN)                            && \
     ((defined START_SEC_CODE) || \
      (defined START_SEC_CODE_FAST) || \
      (defined START_SEC_CODE_ISR)    \
))
#error "MemMap.h: Close the former code segment before opening a new one."
#endif

#if((defined CONST_SEC_OPEN)                           && \
     ((defined START_SEC_CONST_8BIT) || \
      (defined START_SEC_CONST_16BIT) || \
      (defined START_SEC_CONST_32BIT) || \
      (defined START_SEC_CONST_UNSPECIFIED) || \
      (defined START_SEC_CONFIG_DATA_UNSPECIFIED) || \
      (defined START_SEC_CONST_FAST_8BIT) || \
      (defined START_SEC_CONST_FAST_16BIT) || \
      (defined START_SEC_CONST_FAST_32BIT) || \
      (defined START_SEC_CONST_FAST_UNSPECIFIED) || \
      (defined START_SEC_CONST_PBCFG)    \
))
#error "MemMap.h: Close the former const segment before opening a new one."
#endif

#if((defined VAR_SEC_OPEN)                             && \
     ((defined START_SEC_VAR_INIT_8BIT) || \
      (defined START_SEC_VAR_INIT_16BIT) || \
      (defined START_SEC_VAR_INIT_32BIT) || \
      (defined START_SEC_VAR_INIT_UNSPECIFIED) || \
      (defined START_SEC_VAR_NOINIT_8BIT) || \
      (defined START_SEC_VAR_NOINIT_16BIT) || \
      (defined START_SEC_VAR_NOINIT_32BIT) || \
      (defined START_SEC_VAR_NOINIT_UNSPECIFIED) || \
      (defined START_SEC_VAR_NO_INIT_8BIT) || \
      (defined START_SEC_VAR_NO_INIT_16BIT) || \
      (defined START_SEC_VAR_NO_INIT_32BIT) || \
      (defined START_SEC_VAR_NO_INIT_UNSPECIFIED) || \
      (defined START_SEC_VAR_ZERO_INIT_8BIT) || \
      (defined START_SEC_VAR_ZERO_INIT_16BIT) || \
      (defined START_SEC_VAR_ZERO_INIT_32BIT) || \
      (defined START_SEC_VAR_ZERO_INIT_UNSPECIFIED) || \
      (defined START_SEC_VAR_FAST_INIT_8BIT) || \
      (defined START_SEC_VAR_FAST_INIT_16BIT) || \
      (defined START_SEC_VAR_FAST_INIT_32BIT) || \
      (defined START_SEC_VAR_FAST_INIT_UNSPECIFIED) || \
      (defined START_SEC_VAR_FAST_NOINIT_8BIT) || \
      (defined START_SEC_VAR_FAST_NOINIT_16BIT) || \
      (defined START_SEC_VAR_FAST_NOINIT_32BIT) || \
      (defined START_SEC_VAR_FAST_NOINIT_UNSPECIFIED) || \
      (defined START_SEC_VAR_FAST_ZERO_INIT_8BIT) || \
      (defined START_SEC_VAR_FAST_ZERO_INIT_16BIT) || \
      (defined START_SEC_VAR_FAST_ZERO_INIT_32BIT) || \
      (defined START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED)    \
))
#error "MemMap.h: Close the former variable segment before opening a new one."
#endif

#ifdef START_SEC_CODE
#define CODE_SEC_OPEN

#undef START_SEC_CODE
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CODE_FAST
#define CODE_SEC_OPEN

#undef START_SEC_CODE_FAST
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CODE_ISR
#define CODE_SEC_OPEN

#undef START_SEC_CODE_ISR
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_8BIT
#define CONST_SEC_OPEN

#undef START_SEC_CONST_8BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_16BIT
#define CONST_SEC_OPEN

#undef START_SEC_CONST_16BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_32BIT
#define CONST_SEC_OPEN

#undef START_SEC_CONST_32BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_UNSPECIFIED
#define CONST_SEC_OPEN

#undef START_SEC_CONST_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONFIG_DATA_UNSPECIFIED
#define CONST_SEC_OPEN

#undef START_SEC_CONFIG_DATA_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_FAST_8BIT
#define CONST_SEC_OPEN

#undef START_SEC_CONST_FAST_8BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_FAST_16BIT
#define CONST_SEC_OPEN

#undef START_SEC_CONST_FAST_16BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_FAST_32BIT
#define CONST_SEC_OPEN

#undef START_SEC_CONST_FAST_32BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_FAST_UNSPECIFIED
#define CONST_SEC_OPEN

#undef START_SEC_CONST_FAST_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_CONST_PBCFG
#define CONST_SEC_OPEN

#undef START_SEC_CONST_PBCFG
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_INIT_8BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_INIT_8BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_INIT_16BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_INIT_16BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_INIT_32BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_INIT_32BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_INIT_UNSPECIFIED
#define VAR_SEC_OPEN

#undef START_SEC_VAR_INIT_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_NOINIT_8BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_NOINIT_8BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_NOINIT_16BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_NOINIT_16BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_NOINIT_32BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_NOINIT_32BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_NOINIT_UNSPECIFIED
#define VAR_SEC_OPEN

#undef START_SEC_VAR_NOINIT_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_NO_INIT_8
#define VAR_SEC_OPEN

#undef START_SEC_VAR_NO_INIT_8
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_NO_INIT_16
#define VAR_SEC_OPEN

#undef START_SEC_VAR_NO_INIT_16
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_NO_INIT_32
#define VAR_SEC_OPEN

#undef START_SEC_VAR_NO_INIT_32
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_NO_INIT_UNSPECIFIED
#define VAR_SEC_OPEN

#undef START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_ZERO_INIT_8BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_ZERO_INIT_8BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_ZERO_INIT_16BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_ZERO_INIT_16BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_ZERO_INIT_32BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_ZERO_INIT_32BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define VAR_SEC_OPEN

#undef START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_INIT_8BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_INIT_8BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_INIT_16BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_INIT_16BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_INIT_32BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_INIT_32BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_INIT_UNSPECIFIED
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_INIT_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_NOINIT_8BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_NOINIT_8BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_NOINIT_16BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_NOINIT_16BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_NOINIT_32BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_NOINIT_32BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_ZERO_INIT_8BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_ZERO_INIT_8BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_ZERO_INIT_16BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_ZERO_INIT_16BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_ZERO_INIT_32BIT
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_ZERO_INIT_32BIT
#undef MEMMAP_ERROR
#endif

#ifdef START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#define VAR_SEC_OPEN

#undef START_SEC_VAR_FAST_ZERO_INIT_UNSPECIFIED
#undef MEMMAP_ERROR
#endif

#ifdef STOP_SEC_CODE
#undef CODE_SEC_OPEN

#undef STOP_SEC_CODE
#undef MEMMAP_ERROR
#endif

#ifdef STOP_SEC_CONST
#undef CONST_SEC_OPEN

#undef STOP_SEC_CONST
#undef MEMMAP_ERROR
#endif

#ifdef STOP_SEC_VAR
#undef VAR_SEC_OPEN

#undef STOP_SEC_VAR
#undef MEMMAP_ERROR
#endif

#ifdef MEMMAP_ERROR
#error "MemMap.h, wrong pragma command"
#endif

/******************************************************************************/
/* MACROS                                                                     */
/******************************************************************************/

/******************************************************************************/
/* TYPEDEFS                                                                   */
/******************************************************************************/

/******************************************************************************/
/* CONSTS                                                                     */
/******************************************************************************/

/******************************************************************************/
/* PARAMS                                                                     */
/******************************************************************************/

/******************************************************************************/
/* OBJECTS                                                                    */
/******************************************************************************/

/******************************************************************************/
/* FUNCTIONS                                                                  */
/******************************************************************************/

/******************************************************************************/
/* EOF                                                                        */
/******************************************************************************/

